theme: jekyll-theme-hacker

avatar: https://avatars1.githubusercontent.com/u/15436007?s=460&v=4

footer-links:
  email: m.bouvier.dev@gmail.com
  twitter: marcbouvier_
  stackoverflow: users/444769/marc-bouvier
  github: marc-bouvier
  linkedin: profileofmarcbouvier
